title: "Podcast Associació Veïnal Can Gaietà"
description: "Podcast informatiu de l'Associació Veïnal de Can Gaietà de Tiana. Contingut generat amb IA basant-se en fonts oficials."
baseurl: "/podcast"
url: "https://cangaieta.github.io"

# Informació del podcast
podcast:
  title: "Podcast Associació Veïnal Can Gaietà"
  subtitle: "Informació transparent sobre el que passa a Tiana"
  description: "Podcast informatiu que ofereix una font d'informació alternativa sobre els esdeveniments del poble, discussions del ple i sessions del CAUT. Contingut generat amb Google NotebookLM basant-se en fonts oficials."
  author: "Associació Veïnal de Can Gaietà"
  email: "podcast@cangaieta.cat"
  website: "https://cangaieta.cat"
  language: "ca-ES"
  category: "News & Politics"
  image: "/assets/logo-podcast.png"

# GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Configuració Jekyll
markdown: kramdown
highlighter: rouge
theme: minima

# Collections
collections:
  episodes:
    output: true
    permalink: /episodi/:name/

defaults:
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode