title: "Podcast Associació Veïnal Can Gaietà"
description: "Podcast per fomentar l'esperit crític sobre els esdeveniments de Tiana. Contingut 100% generat amb IA (NotebookLM + Whisper + Claude). Busca la veritat per tu mateix."
baseurl: "/podcast"
url: "https://cangaieta.github.io"

# Informació del podcast
podcast:
  title: "Podcast Associació Veïnal Can Gaietà"
  subtitle: "Esperit crític sobre el que passa a Tiana"
  description: "Podcast per fomentar el debat crític sobre els esdeveniments locals. Analitzem discussions del ple i sessions del CAUT des de diferents perspectives. Contingut 100% generat amb IA (NotebookLM + Whisper + Claude). Et convidem a buscar la veritat per tu mateix."
  author: "Associació Veïnal de Can Gaietà"
  email: "podcast@cangaieta.cat"
  website: "https://cangaieta.cat"
  language: "ca-ES"
  category: "News & Politics"
  image: "/assets/logo-podcast.png"

# GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Configuració Jekyll
markdown: kramdown
highlighter: rouge
theme: minima

# Collections
collections:
  episodes:
    output: true
    permalink: /episodi/:name/

defaults:
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode